# Generated by Django 2.2.13 on 2020-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_test_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="commit_2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
