# Generated by Django 2.2.13 on 2020-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_commit_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='commit_4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
